spring:
  config:
    import:
      - "aws-parameterstore:/PHOTO_LINER_API/rds/dev/"
      - "aws-parameterstore:/PHOTO_LINER_API/ec2/dev/"
      - "aws-parameterstore:/PHOTO_LINER_API/cdn/dev/"
      - "aws-parameterstore:/PHOTO_LINER_API/s3/dev/"

  cloud:
    aws:
      region:
        static: ap-northeast-2

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}

photo:
  upload:
    base-dir: ${PHOTOS_UPLOAD_URL}

cors:
  allow-url: ${CORS_ALLOW_URL}

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET_NAME}
    cdn:
      base-url: ${CDN_URL}

kakao:
  api:
    rest-api-key: ${REST_API_KEY}
    login-oauth:
      redirect-url: ${REDIRECT_URL}

jwt:
  secret-key: ${SECRET_KEY}
  access-token:
    expiration-time: ${EXPIRATION_TIME}

application:
  base-url: ${BASE_URL}
